package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuDe generated by hbm2java
 */
@Entity
@Table(name = "ChuDe")
public class ChuDe implements java.io.Serializable {

	private int id;
	private NhanVien nhanVien;
	private Serializable ten;
	private Set khoaHocs = new HashSet(0);

	public ChuDe() {
	}

	public ChuDe(int id, Serializable ten) {
		this.id = id;
		this.ten = ten;
	}

	public ChuDe(int id, NhanVien nhanVien, Serializable ten, Set khoaHocs) {
		this.id = id;
		this.nhanVien = nhanVien;
		this.ten = ten;
		this.khoaHocs = khoaHocs;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdNhanVien")
	public NhanVien getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	@Column(name = "Ten", nullable = false)
	public Serializable getTen() {
		return this.ten;
	}

	public void setTen(Serializable ten) {
		this.ten = ten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuDe")
	public Set getKhoaHocs() {
		return this.khoaHocs;
	}

	public void setKhoaHocs(Set khoaHocs) {
		this.khoaHocs = khoaHocs;
	}

}
