package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DangKyThi generated by hbm2java
 */
@Entity
@Table(name = "DangKyThi")
public class DangKyThi implements java.io.Serializable {

	private DangKyThiId id;
	private HocVien hocVien;
	private KyThi kyThi;
	private int daDangKy;
	private Double diem;

	public DangKyThi() {
	}

	public DangKyThi(DangKyThiId id, HocVien hocVien, KyThi kyThi, int daDangKy) {
		this.id = id;
		this.hocVien = hocVien;
		this.kyThi = kyThi;
		this.daDangKy = daDangKy;
	}

	public DangKyThi(DangKyThiId id, HocVien hocVien, KyThi kyThi,
			int daDangKy, Double diem) {
		this.id = id;
		this.hocVien = hocVien;
		this.kyThi = kyThi;
		this.daDangKy = daDangKy;
		this.diem = diem;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idKyThi", column = @Column(name = "IdKyThi", nullable = false)),
			@AttributeOverride(name = "idHocVien", column = @Column(name = "IdHocVien", nullable = false)) })
	public DangKyThiId getId() {
		return this.id;
	}

	public void setId(DangKyThiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdHocVien", nullable = false, insertable = false, updatable = false)
	public HocVien getHocVien() {
		return this.hocVien;
	}

	public void setHocVien(HocVien hocVien) {
		this.hocVien = hocVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdKyThi", nullable = false, insertable = false, updatable = false)
	public KyThi getKyThi() {
		return this.kyThi;
	}

	public void setKyThi(KyThi kyThi) {
		this.kyThi = kyThi;
	}

	@Column(name = "DaDangKy", nullable = false)
	public int getDaDangKy() {
		return this.daDangKy;
	}

	public void setDaDangKy(int daDangKy) {
		this.daDangKy = daDangKy;
	}

	@Column(name = "Diem", precision = 53, scale = 0)
	public Double getDiem() {
		return this.diem;
	}

	public void setDiem(Double diem) {
		this.diem = diem;
	}

}
