package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DangKyKhoaHocId generated by hbm2java
 */
@Embeddable
public class DangKyKhoaHocId implements java.io.Serializable {

	private int idHocVien;
	private int idKhoaHoc;

	public DangKyKhoaHocId() {
	}

	public DangKyKhoaHocId(int idHocVien, int idKhoaHoc) {
		this.idHocVien = idHocVien;
		this.idKhoaHoc = idKhoaHoc;
	}

	@Column(name = "IdHocVien", nullable = false)
	public int getIdHocVien() {
		return this.idHocVien;
	}

	public void setIdHocVien(int idHocVien) {
		this.idHocVien = idHocVien;
	}

	@Column(name = "IdKhoaHoc", nullable = false)
	public int getIdKhoaHoc() {
		return this.idKhoaHoc;
	}

	public void setIdKhoaHoc(int idKhoaHoc) {
		this.idKhoaHoc = idKhoaHoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DangKyKhoaHocId))
			return false;
		DangKyKhoaHocId castOther = (DangKyKhoaHocId) other;

		return (this.getIdHocVien() == castOther.getIdHocVien())
				&& (this.getIdKhoaHoc() == castOther.getIdKhoaHoc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHocVien();
		result = 37 * result + this.getIdKhoaHoc();
		return result;
	}

}
