package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HocVien generated by hbm2java
 */
@Entity
@Table(name = "HocVien")
public class HocVien implements java.io.Serializable {

	private int id;
	private TaiKhoan taiKhoan;
	private Serializable hoTen;
	private Serializable diaChi;
	private String soDienThoai;
	private Date ngaySinh;
	private Serializable gioiTinh;
	private Set phanHoiHocViens = new HashSet(0);
	private Set dangKyKhoaHocs = new HashSet(0);
	private Set dangKyThis = new HashSet(0);

	public HocVien() {
	}

	public HocVien(int id, TaiKhoan taiKhoan, Serializable hoTen) {
		this.id = id;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
	}

	public HocVien(int id, TaiKhoan taiKhoan, Serializable hoTen,
			Serializable diaChi, String soDienThoai, Date ngaySinh,
			Serializable gioiTinh, Set phanHoiHocViens, Set dangKyKhoaHocs,
			Set dangKyThis) {
		this.id = id;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.phanHoiHocViens = phanHoiHocViens;
		this.dangKyKhoaHocs = dangKyKhoaHocs;
		this.dangKyThis = dangKyThis;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TaiKhoan", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "HoTen", nullable = false)
	public Serializable getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(Serializable hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "DiaChi")
	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SoDienThoai", length = 20)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GioiTinh")
	public Serializable getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Serializable gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocVien")
	public Set getPhanHoiHocViens() {
		return this.phanHoiHocViens;
	}

	public void setPhanHoiHocViens(Set phanHoiHocViens) {
		this.phanHoiHocViens = phanHoiHocViens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocVien")
	public Set getDangKyKhoaHocs() {
		return this.dangKyKhoaHocs;
	}

	public void setDangKyKhoaHocs(Set dangKyKhoaHocs) {
		this.dangKyKhoaHocs = dangKyKhoaHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocVien")
	public Set getDangKyThis() {
		return this.dangKyThis;
	}

	public void setDangKyThis(Set dangKyThis) {
		this.dangKyThis = dangKyThis;
	}

}
