package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KhoaHoc generated by hbm2java
 */
@Entity
@Table(name = "KhoaHoc")
public class KhoaHoc implements java.io.Serializable {

	private int id;
	private ChuDe chuDe;
	private Serializable ten;
	private Date ngayBatDau;
	private Integer khoa;
	private Date ngayKetThuc;
	private Set dangKyKhoaHocs = new HashSet(0);
	private Set lichHocs = new HashSet(0);
	private Set thongBaoKhoaHocs = new HashSet(0);

	public KhoaHoc() {
	}

	public KhoaHoc(int id, ChuDe chuDe, Serializable ten) {
		this.id = id;
		this.chuDe = chuDe;
		this.ten = ten;
	}

	public KhoaHoc(int id, ChuDe chuDe, Serializable ten, Date ngayBatDau,
			Integer khoa, Date ngayKetThuc, Set dangKyKhoaHocs, Set lichHocs,
			Set thongBaoKhoaHocs) {
		this.id = id;
		this.chuDe = chuDe;
		this.ten = ten;
		this.ngayBatDau = ngayBatDau;
		this.khoa = khoa;
		this.ngayKetThuc = ngayKetThuc;
		this.dangKyKhoaHocs = dangKyKhoaHocs;
		this.lichHocs = lichHocs;
		this.thongBaoKhoaHocs = thongBaoKhoaHocs;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ChuDe", nullable = false)
	public ChuDe getChuDe() {
		return this.chuDe;
	}

	public void setChuDe(ChuDe chuDe) {
		this.chuDe = chuDe;
	}

	@Column(name = "Ten", nullable = false)
	public Serializable getTen() {
		return this.ten;
	}

	public void setTen(Serializable ten) {
		this.ten = ten;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayBatDau", length = 10)
	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	@Column(name = "Khoa")
	public Integer getKhoa() {
		return this.khoa;
	}

	public void setKhoa(Integer khoa) {
		this.khoa = khoa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayKetThuc", length = 10)
	public Date getNgayKetThuc() {
		return this.ngayKetThuc;
	}

	public void setNgayKetThuc(Date ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoaHoc")
	public Set getDangKyKhoaHocs() {
		return this.dangKyKhoaHocs;
	}

	public void setDangKyKhoaHocs(Set dangKyKhoaHocs) {
		this.dangKyKhoaHocs = dangKyKhoaHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoaHoc")
	public Set getLichHocs() {
		return this.lichHocs;
	}

	public void setLichHocs(Set lichHocs) {
		this.lichHocs = lichHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoaHoc")
	public Set getThongBaoKhoaHocs() {
		return this.thongBaoKhoaHocs;
	}

	public void setThongBaoKhoaHocs(Set thongBaoKhoaHocs) {
		this.thongBaoKhoaHocs = thongBaoKhoaHocs;
	}

}
