package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "NhanVien")
public class NhanVien implements java.io.Serializable {

	private int id;
	private VaiTro vaiTro;
	private TaiKhoan taiKhoan;
	private Serializable hoTen;
	private Serializable diaChi;
	private String soDienThoai;
	private BigDecimal luong;
	private Date ngaySinh;
	private Serializable gioiTinh;
	private Set chuDes = new HashSet(0);

	public NhanVien() {
	}

	public NhanVien(int id, VaiTro vaiTro, Serializable hoTen) {
		this.id = id;
		this.vaiTro = vaiTro;
		this.hoTen = hoTen;
	}

	public NhanVien(int id, VaiTro vaiTro, TaiKhoan taiKhoan,
			Serializable hoTen, Serializable diaChi, String soDienThoai,
			BigDecimal luong, Date ngaySinh, Serializable gioiTinh, Set chuDes) {
		this.id = id;
		this.vaiTro = vaiTro;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.luong = luong;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.chuDes = chuDes;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VaiTro", nullable = false)
	public VaiTro getVaiTro() {
		return this.vaiTro;
	}

	public void setVaiTro(VaiTro vaiTro) {
		this.vaiTro = vaiTro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TaiKhoan")
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "HoTen", nullable = false)
	public Serializable getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(Serializable hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "DiaChi")
	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SoDienThoai", length = 20)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Column(name = "Luong", scale = 4)
	public BigDecimal getLuong() {
		return this.luong;
	}

	public void setLuong(BigDecimal luong) {
		this.luong = luong;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GioiTinh")
	public Serializable getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Serializable gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanVien")
	public Set getChuDes() {
		return this.chuDes;
	}

	public void setChuDes(Set chuDes) {
		this.chuDes = chuDes;
	}

}
