package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuyenHan generated by hbm2java
 */
@Entity
@Table(name = "QuyenHan")
public class QuyenHan implements java.io.Serializable {

	private int id;
	private Serializable ten;
	private Set taiKhoans = new HashSet(0);

	public QuyenHan() {
	}

	public QuyenHan(int id, Serializable ten) {
		this.id = id;
		this.ten = ten;
	}

	public QuyenHan(int id, Serializable ten, Set taiKhoans) {
		this.id = id;
		this.ten = ten;
		this.taiKhoans = taiKhoans;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Ten", nullable = false)
	public Serializable getTen() {
		return this.ten;
	}

	public void setTen(Serializable ten) {
		this.ten = ten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quyenHan")
	public Set getTaiKhoans() {
		return this.taiKhoans;
	}

	public void setTaiKhoans(Set taiKhoans) {
		this.taiKhoans = taiKhoans;
	}

}
