package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThongBaoKhoaHocId generated by hbm2java
 */
@Embeddable
public class ThongBaoKhoaHocId implements java.io.Serializable {

	private int idKhoaHoc;
	private Date thoiGian;

	public ThongBaoKhoaHocId() {
	}

	public ThongBaoKhoaHocId(int idKhoaHoc, Date thoiGian) {
		this.idKhoaHoc = idKhoaHoc;
		this.thoiGian = thoiGian;
	}

	@Column(name = "IdKhoaHoc", nullable = false)
	public int getIdKhoaHoc() {
		return this.idKhoaHoc;
	}

	public void setIdKhoaHoc(int idKhoaHoc) {
		this.idKhoaHoc = idKhoaHoc;
	}

	@Column(name = "ThoiGian", nullable = false, length = 23)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThongBaoKhoaHocId))
			return false;
		ThongBaoKhoaHocId castOther = (ThongBaoKhoaHocId) other;

		return (this.getIdKhoaHoc() == castOther.getIdKhoaHoc())
				&& ((this.getThoiGian() == castOther.getThoiGian()) || (this
						.getThoiGian() != null
						&& castOther.getThoiGian() != null && this
						.getThoiGian().equals(castOther.getThoiGian())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdKhoaHoc();
		result = 37 * result
				+ (getThoiGian() == null ? 0 : this.getThoiGian().hashCode());
		return result;
	}

}
