package pojo;

// Generated Jun 3, 2015 6:16:54 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VaiTro generated by hbm2java
 */
@Entity
@Table(name = "VaiTro")
public class VaiTro implements java.io.Serializable {

	private int id;
	private Serializable ten;
	private Set nhanViens = new HashSet(0);

	public VaiTro() {
	}

	public VaiTro(int id, Serializable ten) {
		this.id = id;
		this.ten = ten;
	}

	public VaiTro(int id, Serializable ten, Set nhanViens) {
		this.id = id;
		this.ten = ten;
		this.nhanViens = nhanViens;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Ten", nullable = false)
	public Serializable getTen() {
		return this.ten;
	}

	public void setTen(Serializable ten) {
		this.ten = ten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vaiTro")
	public Set getNhanViens() {
		return this.nhanViens;
	}

	public void setNhanViens(Set nhanViens) {
		this.nhanViens = nhanViens;
	}

}
