package pojo;

// Generated May 31, 2015 10:32:38 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChuDe generated by hbm2java
 */
@Entity
@Table(name = "ChuDe")
public class ChuDe implements java.io.Serializable {

	private int id;
	private NhanVien nhanVien;
	private String ten;
	private Set<KhoaHoc> khoaHocs = new HashSet<KhoaHoc>(0);

	public ChuDe() {
	}

	public ChuDe(int id, String ten) {
		this.id = id;
		this.ten = ten;
	}

	public ChuDe(int id, NhanVien nhanVien, String ten, Set<KhoaHoc> khoaHocs) {
		this.id = id;
		this.nhanVien = nhanVien;
		this.ten = ten;
		this.khoaHocs = khoaHocs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdNhanVien")
	public NhanVien getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	@Column(name = "Ten", nullable = false)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chuDe")
	public Set<KhoaHoc> getKhoaHocs() {
		return this.khoaHocs;
	}

	public void setKhoaHocs(Set<KhoaHoc> khoaHocs) {
		this.khoaHocs = khoaHocs;
	}

}
