package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DangKyKhoaHoc generated by hbm2java
 */
@Entity
@Table(name = "DangKyKhoaHoc")
public class DangKyKhoaHoc implements java.io.Serializable {

	private DangKyKhoaHocId id;
	private HocVien hocVien;
	private KhoaHoc khoaHoc;
	private int daDangKy;

	public DangKyKhoaHoc() {
	}

	public DangKyKhoaHoc(DangKyKhoaHocId id, HocVien hocVien, KhoaHoc khoaHoc,
			int daDangKy) {
		this.id = id;
		this.hocVien = hocVien;
		this.khoaHoc = khoaHoc;
		this.daDangKy = daDangKy;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idHocVien", column = @Column(name = "IdHocVien", nullable = false)),
			@AttributeOverride(name = "idKhoaHoc", column = @Column(name = "IdKhoaHoc", nullable = false)) })
	public DangKyKhoaHocId getId() {
		return this.id;
	}

	public void setId(DangKyKhoaHocId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdHocVien", nullable = false, insertable = false, updatable = false)
	public HocVien getHocVien() {
		return this.hocVien;
	}

	public void setHocVien(HocVien hocVien) {
		this.hocVien = hocVien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdKhoaHoc", nullable = false, insertable = false, updatable = false)
	public KhoaHoc getKhoaHoc() {
		return this.khoaHoc;
	}

	public void setKhoaHoc(KhoaHoc khoaHoc) {
		this.khoaHoc = khoaHoc;
	}

	@Column(name = "DaDangKy", nullable = false)
	public int getDaDangKy() {
		return this.daDangKy;
	}

	public void setDaDangKy(int daDangKy) {
		this.daDangKy = daDangKy;
	}

}
