package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HocVien generated by hbm2java
 */
@Entity
@Table(name = "HocVien")
public class HocVien implements java.io.Serializable {

	private int id;
	private TaiKhoan taiKhoan;
	private String hoTen;
	private String diaChi;
	private String soDienThoai;
	private Date ngaySinh;
	private String gioiTinh;
	private Set<PhanHoiHocVien> phanHoiHocViens = new HashSet<PhanHoiHocVien>(0);
	private Set<DangKyKhoaHoc> dangKyKhoaHocs = new HashSet<DangKyKhoaHoc>(0);
	private Set<DangKyThi> dangKyThis = new HashSet<DangKyThi>(0);

	public HocVien() {
	}

	public HocVien(int id, TaiKhoan taiKhoan, String hoTen) {
		this.id = id;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
	}

	public HocVien(int id, TaiKhoan taiKhoan, String hoTen,
			String diaChi, String soDienThoai, Date ngaySinh,
			String gioiTinh, Set<PhanHoiHocVien> phanHoiHocViens, Set<DangKyKhoaHoc> dangKyKhoaHocs,
			Set<DangKyThi> dangKyThis) {
		this.id = id;
		this.taiKhoan = taiKhoan;
		this.hoTen = hoTen;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.phanHoiHocViens = phanHoiHocViens;
		this.dangKyKhoaHocs = dangKyKhoaHocs;
		this.dangKyThis = dangKyThis;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TaiKhoan", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "HoTen", nullable = false)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "DiaChi")
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SoDienThoai", length = 20)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GioiTinh")
	public String getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(String gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocVien")
	public Set<PhanHoiHocVien> getPhanHoiHocViens() {
		return this.phanHoiHocViens;
	}

	public void setPhanHoiHocViens(Set<PhanHoiHocVien> phanHoiHocViens) {
		this.phanHoiHocViens = phanHoiHocViens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocVien")
	public Set<DangKyKhoaHoc> getDangKyKhoaHocs() {
		return this.dangKyKhoaHocs;
	}

	public void setDangKyKhoaHocs(Set<DangKyKhoaHoc> dangKyKhoaHocs) {
		this.dangKyKhoaHocs = dangKyKhoaHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocVien")
	public Set<DangKyThi> getDangKyThis() {
		return this.dangKyThis;
	}

	public void setDangKyThis(Set<DangKyThi> dangKyThis) {
		this.dangKyThis = dangKyThis;
	}

}
