package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KhoaHoc generated by hbm2java
 */
@Entity
@Table(name = "KhoaHoc")
public class KhoaHoc implements java.io.Serializable {

	private int id;
	private ChuDe chuDe;
	private String ten;
	private Date ngayBatDau;
	private Date ngayKetThuc;
	private Integer khoa;
	private Set<DangKyKhoaHoc> dangKyKhoaHocs = new HashSet<DangKyKhoaHoc>(0);
	private Set<LichHoc> lichHocs = new HashSet<LichHoc>(0);
	private Set<ThongBaoKhoaHoc> thongBaoKhoaHocs = new HashSet<ThongBaoKhoaHoc>(0);

	public KhoaHoc() {
	}

	public KhoaHoc(int id, ChuDe chuDe, String ten) {
		this.id = id;
		this.chuDe = chuDe;
		this.ten = ten;
	}

	public KhoaHoc(int id, ChuDe chuDe, String ten,
			Date ngayBatDau,Date ngayKetThuc, Integer khoa, Set<DangKyKhoaHoc> dangKyKhoaHocs, Set<LichHoc> lichHocs,
			Set<ThongBaoKhoaHoc> thongBaoKhoaHocs) {
		this.id = id;
		this.chuDe = chuDe;
		this.ten = ten;
		this.ngayBatDau = ngayBatDau;
		this.ngayKetThuc = ngayKetThuc;
		this.khoa = khoa;
		this.dangKyKhoaHocs = dangKyKhoaHocs;
		this.lichHocs = lichHocs;
		this.thongBaoKhoaHocs = thongBaoKhoaHocs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ChuDe", nullable = false)
	public ChuDe getChuDe() {
		return this.chuDe;
	}

	public void setChuDe(ChuDe chuDe) {
		this.chuDe = chuDe;
	}

	@Column(name = "Ten", nullable = false)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayBatDau", length = 10)
	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "NgayKetThuc", length = 10)
	public Date getNgayKetThuc() {
		return ngayKetThuc;
	}


	public void setNgayKetThuc(Date ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}

	@Column(name = "Khoa")
	public Integer getKhoa() {
		return this.khoa;
	}

	public void setKhoa(Integer khoa) {
		this.khoa = khoa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoaHoc")
	public Set<DangKyKhoaHoc> getDangKyKhoaHocs() {
		return this.dangKyKhoaHocs;
	}

	public void setDangKyKhoaHocs(Set<DangKyKhoaHoc> dangKyKhoaHocs) {
		this.dangKyKhoaHocs = dangKyKhoaHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoaHoc")
	public Set<LichHoc> getLichHocs() {
		return this.lichHocs;
	}

	public void setLichHocs(Set<LichHoc> lichHocs) {
		this.lichHocs = lichHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoaHoc")
	public Set<ThongBaoKhoaHoc> getThongBaoKhoaHocs() {
		return this.thongBaoKhoaHocs;
	}

	public void setThongBaoKhoaHocs(Set<ThongBaoKhoaHoc> thongBaoKhoaHocs) {
		this.thongBaoKhoaHocs = thongBaoKhoaHocs;
	}

}
