package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KyThi generated by hbm2java
 */
@Entity
@Table(name = "KyThi")
public class KyThi implements java.io.Serializable {

	private int id;
	private String ten;
	private Date thoiGianThi;
	private String diaDiem;
	private Integer soLuongDuThi;
	private Set<DangKyThi> dangKyThis = new HashSet<DangKyThi>(0);

	public KyThi() {
	}

	public KyThi(int id, String ten) {
		this.id = id;
		this.ten = ten;
	}

	public KyThi(int id, String ten, Date thoiGianThi,
			String diaDiem, Integer soLuongDuThi, Set<DangKyThi> dangKyThis) {
		this.id = id;
		this.ten = ten;
		this.thoiGianThi = thoiGianThi;
		this.diaDiem = diaDiem;
		this.soLuongDuThi = soLuongDuThi;
		this.dangKyThis = dangKyThis;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Ten", nullable = false)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianThi", length = 23)
	public Date getThoiGianThi() {
		return this.thoiGianThi;
	}

	public void setThoiGianThi(Date thoiGianThi) {
		this.thoiGianThi = thoiGianThi;
	}

	@Column(name = "DiaDiem")
	public String getDiaDiem() {
		return this.diaDiem;
	}

	public void setDiaDiem(String diaDiem) {
		this.diaDiem = diaDiem;
	}

	@Column(name = "SoLuongDuThi")
	public Integer getSoLuongDuThi() {
		return this.soLuongDuThi;
	}

	public void setSoLuongDuThi(Integer soLuongDuThi) {
		this.soLuongDuThi = soLuongDuThi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kyThi")
	public Set<DangKyThi> getDangKyThis() {
		return this.dangKyThis;
	}

	public void setDangKyThis(Set<DangKyThi> dangKyThis) {
		this.dangKyThis = dangKyThis;
	}

}
