package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LichHocId generated by hbm2java
 */
@Embeddable
public class LichHocId implements java.io.Serializable {

	private int idKhoaHoc;
	private int buoiHoc;

	public LichHocId() {
	}

	public LichHocId(int idKhoaHoc, int buoiHoc) {
		this.idKhoaHoc = idKhoaHoc;
		this.buoiHoc = buoiHoc;
	}

	@Column(name = "IdKhoaHoc", nullable = false)
	public int getIdKhoaHoc() {
		return this.idKhoaHoc;
	}

	public void setIdKhoaHoc(int idKhoaHoc) {
		this.idKhoaHoc = idKhoaHoc;
	}

	@Column(name = "BuoiHoc", nullable = false)
	public int getBuoiHoc() {
		return this.buoiHoc;
	}

	public void setBuoiHoc(int buoiHoc) {
		this.buoiHoc = buoiHoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LichHocId))
			return false;
		LichHocId castOther = (LichHocId) other;

		return (this.getIdKhoaHoc() == castOther.getIdKhoaHoc())
				&& (this.getBuoiHoc() == castOther.getBuoiHoc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdKhoaHoc();
		result = 37 * result + this.getBuoiHoc();
		return result;
	}

}
