package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LichHoc generated by hbm2java
 */
@Entity
@Table(name = "LichHoc")
public class LichHoc implements java.io.Serializable {

	private LichHocId id;
	private KhoaHoc khoaHoc;
	private Date thoiGianHoc;
	private String phongHoc;

	public LichHoc() {
	}

	public LichHoc(LichHocId id, KhoaHoc khoaHoc) {
		this.id = id;
		this.khoaHoc = khoaHoc;
	}

	public LichHoc(LichHocId id, KhoaHoc khoaHoc, Date thoiGianHoc,
			String phongHoc) {
		this.id = id;
		this.khoaHoc = khoaHoc;
		this.thoiGianHoc = thoiGianHoc;
		this.phongHoc = phongHoc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idKhoaHoc", column = @Column(name = "IdKhoaHoc", nullable = false)),
			@AttributeOverride(name = "buoiHoc", column = @Column(name = "BuoiHoc", nullable = false)) })
	public LichHocId getId() {
		return this.id;
	}

	public void setId(LichHocId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdKhoaHoc", nullable = false, insertable = false, updatable = false)
	public KhoaHoc getKhoaHoc() {
		return this.khoaHoc;
	}

	public void setKhoaHoc(KhoaHoc khoaHoc) {
		this.khoaHoc = khoaHoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianHoc", length = 23)
	public Date getThoiGianHoc() {
		return this.thoiGianHoc;
	}

	public void setThoiGianHoc(Date thoiGianHoc) {
		this.thoiGianHoc = thoiGianHoc;
	}

	@Column(name = "PhongHoc")
	public String getPhongHoc() {
		return this.phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

}
