package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhanHoiHocVien generated by hbm2java
 */
@Entity
@Table(name = "PhanHoiHocVien")
public class PhanHoiHocVien implements java.io.Serializable {

	private PhanHoiHocVienId id;
	private HocVien hocVien;
	private String noiDung;

	public PhanHoiHocVien() {
	}

	public PhanHoiHocVien(PhanHoiHocVienId id, HocVien hocVien) {
		this.id = id;
		this.hocVien = hocVien;
	}

	public PhanHoiHocVien(PhanHoiHocVienId id, HocVien hocVien, String noiDung) {
		this.id = id;
		this.hocVien = hocVien;
		this.noiDung = noiDung;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idHocVien", column = @Column(name = "IdHocVien", nullable = false)),
			@AttributeOverride(name = "thoiGian", column = @Column(name = "ThoiGian", nullable = false, length = 23)) })
	public PhanHoiHocVienId getId() {
		return this.id;
	}

	public void setId(PhanHoiHocVienId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdHocVien", nullable = false, insertable = false, updatable = false)
	public HocVien getHocVien() {
		return this.hocVien;
	}

	public void setHocVien(HocVien hocVien) {
		this.hocVien = hocVien;
	}

	@Column(name = "NoiDung")
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
