package pojo;

// Generated May 27, 2015 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuyenHan generated by hbm2java
 */
@Entity
@Table(name = "QuyenHan")
public class QuyenHan implements java.io.Serializable {

	private int id;
	private String ten;
	private Set<TaiKhoan> taiKhoans = new HashSet<TaiKhoan>(0);

	public QuyenHan() {
	}

	public QuyenHan(int id, String ten) {
		this.id = id;
		this.ten = ten;
	}

	public QuyenHan(int id, String ten, Set<TaiKhoan> taiKhoans) {
		this.id = id;
		this.ten = ten;
		this.taiKhoans = taiKhoans;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Ten", nullable = false)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quyenHan")
	public Set<TaiKhoan> getTaiKhoans() {
		return this.taiKhoans;
	}

	public void setTaiKhoans(Set<TaiKhoan> taiKhoans) {
		this.taiKhoans = taiKhoans;
	}

}
